i18n
shimonhayashi/fjord-books_app pull request #4
Opened 2022-12-16 02:34 UTC by shimonhayashi

2022-12-17 13:46 UTC, u1tnk requested changes

2022-12-17 13:46 UTC, u1tnk commented on config/locales/en.yml
> +    translate:
このtranslateというキー名は自分でつけられたんですよね？
でしたら、translateするためのファイルのキーにこの名前は不要かと思います。

2022-12-17 13:46 UTC, u1tnk commented on config/locales/translation_ja.yml
> +      book: 本  #g
#g というコメントは何を意味するのでしょうか？

2022-12-17 13:46 UTC, u1tnk commented on config/locales/translation_ja.yml
> +ja:
この部分ファイルを分けたのはなぜでしょうか？
機能ごとに分けたりはしますが、今回は小さいですし、ja.ymlも生成後に修正していますよね？でしたら `ja.yml`を修正すれば良いかと思います。

2022-12-19 00:46 UTC, shimonhayashi commented on config/locales/en.yml
> +    translate:
削除しました

2022-12-19 00:46 UTC, shimonhayashi commented on config/locales/translation_ja.yml
> +      book: 本  #g
参考にしたサイトのファイルについていただけで意味がないので削除しました

2022-12-19 00:46 UTC, shimonhayashi commented on config/locales/translation_ja.yml
> +ja:
ja.ymlに統合しました。

2022-12-19 00:52 UTC, u1tnk approved these changes

2022-12-19 01:20 UTC, merged